name: py-behav-box-v2
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py310haa95532_0
  - eigen=3.3.7=h59b6b97_1
  - fftw=3.3.9=h2bbff1b_1
  - glib=2.69.1=h5dc1a3c_1
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.1.1=py310haa95532_0
  - jpeg=9e=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_4
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libtiff=4.2.0=he0120a3_1
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - numpy-base=1.21.5=py310h206c741_3
  - opencv=4.5.5=py310h42e1cb5_0
  - openssl=1.1.1s=h2bbff1b_0
  - pcre=8.45=hd77b12b_0
  - pip=21.2.4=py310haa95532_0
  - pyqt=5.9.2=py310hd77b12b_6
  - python=3.10.4=hbb2ffb3_0
  - pywin32=302=py310h2bbff1b_2
  - qt=5.9.7=vc14h73c81de_0
  - scikit-learn=1.1.3=py310hd77b12b_0
  - setuptools=61.2.0=py310haa95532_0
  - sip=4.19.13=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=h2bbff1b_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.3.0
    - aiopipe==0.2.2
    - alembic==1.8.0
    - ansi2html==1.8.0
    - appdirs==1.4.4
    - arrow==1.2.2
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrdict==2.0.1
    - attrs==21.4.0
    - automat==20.2.0
    - ax-platform==0.3.2
    - backcall==0.2.0
    - banal==1.0.6
    - beautifulsoup4==4.11.1
    - botorch==0.8.5
    - cachetools==5.2.0
    - cardinal-pythonlib==1.1.20
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cloudpickle==2.2.0
    - colorama==0.4.5
    - colorlog==6.6.0
    - comm==0.1.3
    - constantly==15.1.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - dash==2.11.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - dataset==1.5.2
    - debugpy==1.6.7
    - decorator==5.1.1
    - deprecated==1.2.13
    - dill==0.3.6
    - dm-tree==0.1.7
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - ffmpeg-python==0.2.0
    - filelock==3.12.2
    - flask==2.2.5
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gpflow==2.6.3
    - gpflux==0.3.0
    - gpytorch==1.10
    - greenlet==1.1.2
    - grpcio==1.50.0
    - h5py==3.7.0
    - hikload==1.1.4
    - hyperlink==21.0.0
    - idna==3.3
    - imutils==0.5.4
    - incremental==21.3.0
    - ipykernel==6.23.3
    - ipython==8.14.0
    - ipywidgets==8.0.6
    - isodate==0.6.1
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - jupyterlab-widgets==3.0.7
    - kaleido==0.2.1
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - lark==1.1.3
    - libclang==14.0.6
    - linear-operator==0.4.0
    - lxml==4.9.1
    - mako==1.2.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mpmath==1.3.0
    - msgspec==0.16.0
    - multipledispatch==0.6.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - nidaqmx==0.6.3
    - numpy==1.25.0
    - oauthlib==3.2.2
    - opencv-contrib-python==4.7.0.72
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.2
    - parso==0.8.3
    - pefile==2022.5.30
    - pendulum==2.1.2
    - pickleshare==0.7.5
    - pillow==9.2.0
    - platformdirs==3.8.0
    - plotly==5.15.0
    - prettytable==3.3.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.1
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==2.1.2
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pypdf2==2.3.1
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyro-api==0.1.2
    - pyro-ppl==1.8.5
    - pyserial==3.5
    - pyserial-asyncio==0.6
    - pyserialtransfer==2.1.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pytzdata==2020.1
    - pywin32-ctypes==0.2.0
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qasync==0.24.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rsa==4.9
    - scipy==1.10.1
    - screeninfo==0.8
    - semantic-version==2.10.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.37
    - sqlparse==0.4.2
    - stack-data==0.6.2
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.1.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.3
    - tensorflow-estimator==2.8.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-probability==0.16.0
    - termcolor==2.0.1
    - torch==2.0.1
    - tornado==6.3.2
    - tqdm==4.64.0
    - traitlets==5.9.0
    - trieste==0.13.0
    - twisted==22.4.0
    - twisted-iocpsupport==1.0.2
    - typeguard==2.13.3
    - typing-extensions==4.2.0
    - urllib3==1.26.10
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - whisker==1.3.0
    - widgetsnbextension==4.0.7
    - win-precise-time==1.4.1
    - wrapt==1.14.1
    - wres==1.0.3
    - xmler==0.2.0
    - zope-interface==5.4.0
