name: py-behav-box-v2
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.5.18.1=py310haa95532_0
  - eigen=3.3.7=h59b6b97_1
  - glib=2.69.1=h5dc1a3c_1
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_4
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libtiff=4.2.0=he0120a3_1
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - numpy-base=1.21.5=py310h206c741_3
  - opencv=4.5.5=py310h42e1cb5_0
  - openssl=1.1.1o=h2bbff1b_0
  - pcre=8.45=hd77b12b_0
  - pip=21.2.4=py310haa95532_0
  - pyqt=5.9.2=py310hd77b12b_6
  - python=3.10.4=hbb2ffb3_0
  - pyzmq=22.3.0=py310hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - setuptools=61.2.0=py310haa95532_0
  - sip=4.19.13=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - alembic==1.8.0
    - appdirs==1.4.4
    - arrow==1.2.2
    - attrdict==2.0.1
    - attrs==21.4.0
    - automat==20.2.0
    - banal==1.0.6
    - beautifulsoup4==4.11.1
    - cardinal-pythonlib==1.1.20
    - colorama==0.4.5
    - colorlog==6.6.0
    - constantly==15.1.0
    - dataset==1.5.2
    - et-xmlfile==1.1.0
    - greenlet==1.1.2
    - hyperlink==21.0.0
    - idna==3.3
    - incremental==21.3.0
    - isodate==0.6.1
    - mako==1.2.0
    - markupsafe==2.1.1
    - nidaqmx==0.6.3
    - numpy==1.22.4
    - openpyxl==3.0.10
    - pandas==1.4.2
    - pendulum==2.1.2
    - prettytable==3.3.0
    - psutil==5.9.1
    - pygame==2.1.2
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pypdf2==2.3.1
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyserial==3.5
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pytzdata==2020.1
    - pyyaml==6.0
    - scipy==1.8.1
    - screeninfo==0.8
    - semantic-version==2.10.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.37
    - sqlparse==0.4.2
    - twisted==22.4.0
    - twisted-iocpsupport==1.0.2
    - typing-extensions==4.2.0
    - wcwidth==0.2.5
    - whisker==1.3.0
    - zope-interface==5.4.0
prefix: C:\ProgramData\Anaconda3\envs\py-behav-box-v2
